spring:
  datasource:
    url: jdbc:sqlite:/app/data/gundam.db?journal_mode=WAL
    driver-class-name: org.sqlite.JDBC
    username: 
    password: 
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 30MB

flyway:
  enabled: true
  locations: classpath:db/migration

app:
  storage:
    root: uploads          # pasta para armazenar fotos
server:
  port: 8080
